name: Run on new release 

on:
  repository_dispatch:
    types:
      - workflow-B

jobs:     
  run-on-new-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
