name: Run on new release 

on: 
  workflow_dispatch:
  release:
    types:
      - published
    repository:
      - 'SiEPIC/SiEPIC_EBeam_PDK'
  
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
  pull_request:
    types:
      - closed 
    branches: [ "master" ]
    paths:
      - 'Dockerfile'

jobs:     
  run-on-new-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
