name: Trigger test workflow

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Run test workflow'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run test.yml
